<?xml version="1.0" ?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.jpmml</groupId>
		<artifactId>jpmml-parent</artifactId>
		<version>1.0.11</version>
	</parent>

	<groupId>org.jpmml</groupId>
	<artifactId>jpmml-codemodel</artifactId>
	<version>1.2.1</version>

	<name>JPMML-CodeModel</name>
	<description>Java utilities for generating, compiling and packaging Java application code</description>
	<url>https://github.com/jpmml/jpmml-codemodel</url>

	<licenses>
		<license>
			<name>BSD 3-Clause License</name>
			<url>http://opensource.org/licenses/BSD-3-Clause</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<id>villu.ruusmann</id>
			<name>Villu Ruusmann</name>
		</developer>
	</developers>

	<scm>
		<connection>scm:git:git@github.com:jpmml/jpmml-codemodel.git</connection>
		<developerConnection>scm:git:git@github.com:jpmml/jpmml-codemodel.git</developerConnection>
		<url>git://github.com/jpmml/jpmml-codemodel.git</url>
		<tag>1.2.1</tag>
	</scm>
	<issueManagement>
		<system>GitHub</system>
		<url>https://github.com/jpmml/jpmml-codemodel/issues</url>
	</issueManagement>

	<properties>
		<guava.version>[21.0,)</guava.version>
		<glassfish-codemodel.version>4.0.6</glassfish-codemodel.version>
		<ecj.version>3.43.0</ecj.version>
		<project.build.outputTimestamp>2025-12-06T16:03:08Z</project.build.outputTimestamp>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>${guava.version}</version>
			<exclusions>
				<exclusion>
					<groupId>*</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>codemodel</artifactId>
			<version>${glassfish-codemodel.version}</version>
		</dependency>

		<dependency>
			<groupId>org.eclipse.jdt</groupId>
			<artifactId>ecj</artifactId>
			<version>${ecj.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
		</plugins>
	</build>

	<profiles>
		<profile>
			<activation>
				<jdk>11</jdk>
			</activation>

			<properties>
				<!-- The last JDK 11 compatible version -->
				<ecj.version>3.33.0</ecj.version>
			</properties>
		</profile>
	</profiles>
</project>
